import asyncio
import logging
from agents import Runner
from agent.CodingAgent import vibe_code
from agent.review_agent import review_code


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger("orchestrator")


MAX_RETRIES = 5

async def execute_agent(user_request: str):

    implementation = None
    review = None

    for cycle in range(1, MAX_RETRIES + 1):
        logger.info("========================================")
        logger.info("Starting cycle %d", cycle)
        logger.info("========================================")

        # -------------------------------------------------
        # VIBE CODER
        # -------------------------------------------------

        if implementation is None:
            vibe_input = user_request

        else:
            vibe_input = f"""Original user request: {user_request} 
            Current implementation:{implementation} 
            Previous code review:{review}

Fix all applicable Critical, High, and Medium issues
identified by the reviewer. Ignore culture checking while reviewing code generated by **Vibe Coder**.

Preserve the original requirements.

Return the complete updated implementation and tests.
"""

        logger.info("[VIBE CODER] Starting")

        vibe_result = await Runner.run(
            vibe_code,
            input=vibe_input,
        )

        implementation = vibe_result.final_output
        print(implementation)
        logger.info("]n[VIBE CODER] Completed\n")

        # -------------------------------------------------
        # REVIEWER
        # -------------------------------------------------

        review_input = f"""
Original user request:

{user_request}


Implementation produced by Vibe Coder:

{implementation}


Review the implementation and tests.

Return PASS if the implementation is acceptable.

Return FAIL if Critical, High issues exist.

Include all findings when returning FAIL.
"""

        logger.info("[REVIEW CODE] Starting")

        review_result = await Runner.run(
            review_code,
            input=review_input,
        )

        review = review_result.final_output

        logger.info("[REVIEW CODE] Completed")
        logger.info("[REVIEW CODE] Result: %s", review)

        # -------------------------------------------------
        # DECISION
        # -------------------------------------------------

        if "PASS" in review:
            logger.info("========================================")
            logger.info("REVIEW PASSED")
            logger.info("========================================")

            return implementation

        logger.warning("Review failed. Sending findings back to Vibe Coder.")

    raise RuntimeError(f"Review did not pass after {MAX_RETRIES} cycles.")


async def main():

    result = await execute_agent("Write a program to add two numbers.")

    print("\n")
    print(result)


if __name__ == "__main__":
    asyncio.run(main())
